# Generated by Django 5.0.6 on 2024-07-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('michoacan', '0002_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearevento',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='evento_imagenes'),
        ),
    ]
